### ISSUE TITLE
Please use asynchronous-defined policies when calling asynchronous ExecuteAsync (and similar) methods.

### ISSUE THREAD

**Issue by ravinderjangra** [RobGibbens/ResilientServices#4]
Throwing exception in my service definition class.
Please use asynchronous-defined policies when calling asynchronous ExecuteAsync (and similar) methods.

**Comment by michael-freidgeim-webjet** [comment]
The error is returned by Polly. They have  Async classes https://github.com/App-vNext/Polly#asynchronous-support (e.g. RetryAsync)  that should be used instead of normal(e.g.Retry)
